name: rentkars
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.14
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  google_maps_flutter: ^2.1.5
  image_picker: ^0.8.5+3
  outline_material_icons_tv: ^0.1.1-nullsafety
  geolocator: ^8.2.1
  firebase_storage: ^10.2.17
  uuid: ^3.0.6
  staggered_grid_view_flutter: ^0.0.4
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  collection: ^1.16.0
  badges: ^2.0.3
  sn_progress_dialog: ^1.0.8
  flutter_datetime_picker: ^1.5.1
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  flutter_stripe: ^3.0.0
  http: ^0.13.4
  country_state_city_picker: ^1.2.8
                                                           

  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/try/
    - assets/images/inapp/
    - assets/images/men/
    - assets/images/women/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
          
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
